### ISSUE TITLE
1.2.10 incompatible with numpy<2

### ISSUE THREAD

**Issue by jimwhite** [stefan-jansen/bcolz-zipline#61]
The recent change to use Numpy's internal API breaks bcolz code that uses that internal API (by design of course).

```
(.venv) jim@jims-air trading_evolved % pip list|grep num                    
numexpr               2.10.1
numpy                 1.26.4
WARNING: There was an error checking the latest version of pip.
(.venv) jim@jims-air trading_evolved % pip list|grep bcol
bcolz-zipline         1.2.10
WARNING: There was an error checking the latest version of pip.
(.venv) jim@jims-air trading_evolved % python -c 'import bcolz;bcolz.test()'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/jim/Projects/trading_evolved/.venv/lib/python3.11/site-packages/bcolz/__init__.py", line 73, in <module>
    from bcolz.arrayprint import (
  File "/Users/jim/Projects/trading_evolved/.venv/lib/python3.11/site-packages/bcolz/arrayprint.py", line 22, in <module>
    from numpy._core import numerictypes as _nt
ImportError: cannot import name 'numerictypes' from 'numpy._core' (/Users/jim/Projects/trading_evolved/.venv/lib/python3.11/site-packages/numpy/_core/__init__.py)
```

I don't think this approach to Numpy 2 compatibility can work.  To fix arrayprint.py we need to just not use Numpy's internal API.

For now I think the thing to do is to continue to use `numpy<2`.  Many folks with large dependency sets (including myself because of a variety of ML libraries) are obliged to do anyhow and I can't just upgrade to `numpy>=2`.

**Comment by stefan-jansen** [comment]
Yes, I've come to realize this as well.

**Comment by jimwhite** [comment]
Works great!  I've just been putting together a Colab notebook for running Zipline so this is very timely.  This first example is from Trading Evolved but I will be giving some ML4T notebooks this treatment too (I'm working on a Polygon.io bundle - https://github.com/fovi-llc/zipline-polygon-bundle).  Thanks!
